services:
  user-service:
    build: ./services/user-service
    ports:
      - "4000:3000"
    environment:
      - MONGO_URI=${USER_MONGO_URI}
    networks:
      - eatsy-network
      
  restaurant-service:
    build: ./services/restaurant-service
    ports:
      - "4001:3000"
    environment:
      - MONGO_URI=${RESTAURANT_MONGO_URI}
    networks:
      - eatsy-network

  order-service:
    build: ./services/order-service
    ports:
      - "4002:3000"
    environment:
      - MONGO_URI=${ORDER_MONGO_URI}
    networks:
      - eatsy-network

  delivery-service:
    build: ./services/delivery-service
    ports:
      - "4003:3000"
    environment:
      - MONGO_URI=${DELIVERY_MONGO_URI}
    networks:
      - eatsy-network

  payment-service:
    build: ./services/payment-service
    ports:
      - "4004:3000"
    environment:
      - MONGO_URI=${PAYMENT_MONGO_URI}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_CUSTOMER_ID=${STRIPE_CUSTOMER_ID}
      - MAIL_USER=${PAYMENT_MAIL_USER}
      - MAIL_PASS=${PAYMENT_MAIL_PASS}
    networks:
      - eatsy-network

  notification-service:
    build: ./services/notification-service
    ports:
      - "4005:3000"
    environment:
      - MONGO_URI=${NOTIFICATION_MONGO_URI}
    networks:
      - eatsy-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - restaurant-service
      - order-service
      - delivery-service
      - payment-service
      - notification-service
    networks:
      - eatsy-network

  web-client:
    build: ./web-client
    ports:
      - "3000:80"
    depends_on:
      - restaurant-service
      - order-service
      - delivery-service
      - payment-service
      - notification-service
    networks:
      - eatsy-network

  admin-panel:
    build: ./admin-panel
    ports:
      - "3001:80"
    depends_on:
      - user-service
      - restaurant-service
      - order-service
      - delivery-service
      - payment-service
      - notification-service
    networks:
      - eatsy-network

networks:
  eatsy-network:
    driver: bridge
